import { useEffect, useRef, useState } from "react";
import { MdOutlineArrowCircleDown } from "react-icons/md";

const Home = () => {
	const [showArrow, setShowArrow] = useState(false);
	const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

	// Start or reset the timer
	const startInactivityTimer = () => {
		if (timerRef.current) clearTimeout(timerRef.current);
		setShowArrow(false); // Hide while interacting

		timerRef.current = setTimeout(() => {
			setShowArrow(true); // Show after 15 seconds of no scrolling
		}, 15000);
	};

	useEffect(() => {
		// Start the initial timer
		startInactivityTimer();

		const handleScroll = () => {
			startInactivityTimer(); // Reset on scroll
		};

		window.addEventListener("scroll", handleScroll);
		return () => {
			window.removeEventListener("scroll", handleScroll);
			if (timerRef.current) clearTimeout(timerRef.current);
		};
	}, []);

	// Shared styles
	const textLeftSectionClass =
		"flex flex-col md:flex-row items-center justify-center text-center dark:text-white min-h-[90vh] py-8 md:py-12";
	const textRightSectionClass =
		"flex flex-col-reverse md:flex-row items-center justify-center text-center dark:text-white min-h-[90vh] py-8 md:py-12";
	const textContainer = "w-full md:w-1/2 px-6 md:px-12 pb-4 md:pb-0";
	const imgContainer = "w-full md:w-1/2 h-full flex justify-center items-center";
	const imgClass = "max-h-[70vh] max-w-3/4 object-contain";

	return (
		<>
			{/* Introduction section */}
			<div className={textLeftSectionClass}>
				{/* Text section */}
				<div className={textContainer}>
					<h1 className='text-4xl font-bold mb-4'>Hi, I'm Arjun</h1>
					<p className='text-lg max-w-md mx-auto'>
						I'm a junior at San Jose State University studying software engineering. I am interested in machine learning, cybersecurity, and full‑stack web development. I recently completed a Software Engineering Co‑Op at Cisco where I built a full‑stack web application for the Cisco hardware compliance team. I used Python Flask, MySQL, and JavaScript, with Nginx serving as a reverse proxy for improved security and scalability.
					</p>
					<p className='text-lg max-w-md mx-auto'>
						I have also published two research papers. In my first paper, I proposed a feedback‑loop system that incorporates high‑fidelity images generated by a diffusion model to enhance zero‑day malware dataset quality. This method showed a 15% improvement in zero‑day attack detection accuracy. My second paper utilizes AI agents to enhance the explainability of network‑based attacks and offers product recommendations and similar CVE vulnerabilities to aid with incident response. I used LangChain ReAct agents and RAG to build an up‑to‑date recommendation pipeline.
					</p>
				</div>

				{/* Image section */}
				<div className={imgContainer}>
					<img
						src='/personal-website/assets/home/Arjun_Sudheer_Professional_Headshot.jpg'
						alt='Professional Headshot'
						className={imgClass}
					/>
				</div>
			</div>

		</>
	);
};

export default Home;
